### ISSUE TITLE
possible to provide an example using greenpack as a package module for golang?

### ISSUE THREAD

**Issue by kolinfluence** [glycerine/greenpack#13]
possible to provide an example using greenpack as a package module for golang?

**Comment by glycerine** [comment]
I'm not sure what you mean when you say "as a package module".  See the demo of how to use greenpack that I created for you, https://github.com/glycerine/greenpack/blob/master/demo/bytes2d.go, and let me know what you are trying to achieve.

Greenpack predates modules, but since it is a code generator, it is usually used simply to add serialization and deserialization methods to an existing package. You can call the functions in the "github.com/glycerine/greenpack/msgp" library if you want/need to. It should import like anything else. If you are having trouble when trying to do that, please provide the specifics of what you tried and what error you encountered.

**Comment by kolinfluence** [comment]
it's amazing work. just tested it out. 

was wondering how to modify the code so that the input [][]byte (and the []bytes in it) are not fixed and unknown?

**Comment by glycerine** [comment]
Glad it helps. Any []bytes stored into the struct will be serialized. It does not matter the sizes of the slices. Whatever you have put in sos will be serialized when sos.MarshalMsg is called.
