### ISSUE TITLE
Timestamp Extension

### ISSUE THREAD

**Issue by ColtonProvias** [glycerine/greenpack#7]
The timestamp extension in this package does not conform to the msgpack spec as of August 2017:

https://github.com/msgpack/msgpack/blob/master/spec.md#timestamp-extension-type

This is a breaking change for this library, even though it isn't a breaking change within the spec.

Maybe the best path would be to add a global flag temporarily that would enable a compatibility mode for backward-compatibility with default behavior being as per msgpack. This should help in transitioning to the standard time representation.

**Comment by glycerine** [comment]
> The timestamp extension in this package does not conform to the msgpack spec as of August 2017.

First, greenpack is not msgpack. It has a different name because it is a different format, and generally more strict, format. While it is desirable to be as compatible as possible, there is no hard requirement to satisfy the whims of recent spec changes in msgpack.

Moreover, there's nothing in the msgpack spec that precludes using the existing extension mechanism and encoding time. tinylib and its descendants have had timestamp support for much longer than this new provision in the msgpack spec.

Design wise,

> In timestamp 64 and timestamp 96 formats, nanoseconds must not be larger than 999999999.

seems like a particularly poor choice, as nanoseconds since the epoch is the most common time representation in many code bases. The new -1 approach will be slower in both time and space.

Nonetheless, if you file a Pull Request, I will certainly consider it.

**Comment by glycerine** [comment]
https://github.com/msgpack/msgpack/issues/240

and

https://github.com/msgpack/msgpack/issues/241

also indicate that the new design is poor, and poorly thought out.

**Comment by glycerine** [comment]
closing as "cannot recommend" at this time.
